export const CATEGORIES_FETCH_START = 'CATEGORIES_FETCH_START';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';

export const ARTICLES_FETCH_START = 'ARTICLES_FETCH_START';
export const ARTICLES_FETCH = 'ARTICLES_FETCH';

export const ARTICLE_FETCH_START = 'ARTICLE_FETCH_START';
export const ARTICLE_FETCH = 'ARTICLE_FETCH';

export const ARTICLE_DELETE_START = 'ARTICLE_DELETE_START';
export const ARTICLE_DELETED = 'ARTICLE_DELETED';

export const ARTICLE_CREATE_START = 'ARTICLE_CREATE_START';
export const ARTICLE_CREATED = 'ARTICLE_CREATED';

export const MENUS_FETCH_START = 'MENUS_FETCH_START';
export const MENUS_FETCHED = 'MENUS_FETCHED';
